### ISSUE TITLE
Implement streaming interface

### ISSUE THREAD

**Issue by wesleytodd** [vmakhaev/reconnectable-websocket#5]
Let me know what do you think about this idea?

It would be nice to expose a standard node-style stream interface.  I was thinking something like this:

``` javascript
var socket = new (require('reconnectable-websocket'))();
var through = require('through2');

socket.pipe(through.obj(function (chunk, enc, done) {
  // Convert a single message into a json object
  done(null, JSON.parse(chunk.toString(enc)));
}));
```

All that is required is extending `ReconnectableWebsocket` from a readable stream and adding a call to `push` when we get a message.  Here are the pros and cons:

| Pros | Cons |
| --- | --- |
| Consistent and well documented interface | Bloat the size of this lib |
| Easily chain functionality off socket messages | Exposes two methods for receiving messages |
| ? any more ? | ? any more ? |

**Comment by vmakhaev** [comment]
Don't there exist packages that wrap web sockets to provide stream interface? I found one https://www.npmjs.com/package/websocketstream, maybe there are more.
I think it makes sense to have this as separate package, because not everyone needs it.

I think the main point of this package is  providing web-socket-like api, but with reconnection ability. This could be a good long-running strategy.

**Comment by wesleytodd** [comment]
I agree with your points.  Unfortunately that module does not have published source, which I had noticed before opening this issue.  Maybe I will spend my time wrapping this module up like they were.  Either way I will research other options :)
